# Generated by Django 3.1.5 on 2021-01-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichyawat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=254),
        ),
    ]
